import {canSelectNode,classNodes,dbSpellUrl,decodeState,encodeState,hasActiveUpperConnection,meetsThreshold,packState,pathState,resetLevels,specNodes,spentPoints,syncPassives,toggleEdge,treeBudgets,unpackState} from "./app.js";

const sample={name:"Vol'jin",talents:[{name:"Mirage",shape:"square",changed:true,threshold:7}]};
const encoded=await encodeState(sample);
console.assert(JSON.stringify(await decodeState(encoded))===JSON.stringify(sample),"compressed share state must round-trip");
const legacy=btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(sample))));
console.assert(JSON.stringify(await decodeState(legacy))===JSON.stringify(sample),"old share links must remain compatible");
const shareBase={version:1,active:"class",trees:{class:{nodes:[{id:"old",name:"Root",spellIds:[1],x:1,points:0},{id:"delete",name:"Delete",spellIds:[2],x:2,points:0}],edges:[]}}},shareEdit=structuredClone(shareBase);
shareEdit.trees.class.nodes[0].x=9;shareEdit.trees.class.nodes.splice(1,1,{id:"new",name:"Custom",x:2,points:1});shareEdit.trees.class.edges.push(["old","new"]);
const restored=unpackState(packState(shareEdit,shareBase),shareBase);
console.assert(restored.trees.class.nodes[0].x===9&&restored.trees.class.nodes[1].name==="Custom"&&!restored.trees.class.nodes.some(node=>node.name==="Delete")&&restored.trees.class.edges.length===1,"packed links must preserve edits, additions, deletions, and connections");
console.assert(toggleEdge([],"a","b").length===1,"connection must be added");
console.assert(toggleEdge([["a","b"]],"a","b").length===0,"connection must be removed");
console.assert([...classNodes,...specNodes].every(node=>node.spellIds?.every(Number.isSafeInteger)),"imported talents must keep their spell IDs");
console.assert(dbSpellUrl(801660)==="https://db.ascension.gg/?spell=801660","spell IDs must link to Ascension DB");
console.assert(spentPoints([{points:1,cost:0},{points:8,cost:1}])===8,"granted talents must not count as spent points");
console.assert(!meetsThreshold({threshold:8},7)&&meetsThreshold({threshold:8},8),"thresholds must unlock at the exact requirement");
console.assert(specNodes.filter(node=>node.cost===0).length===7,"Brewing's seven free nodes must not consume talent points");
console.assert(specNodes.filter(node=>node.passive).map(node=>node.threshold).join() === "0,5,10,15,20","lateral passives must unlock every five spent points");
console.assert(treeBudgets.spec===25,"Brewing must allow 25 spent points when granted talents are free");
const resetNodes=[{points:2,initialPoints:0},{points:0,initialPoints:1}];resetLevels(resetNodes);
console.assert(resetNodes[0].points===0&&resetNodes[1].points===1,"resetting levels must preserve granted starting talents");
const flowNodes=[{id:"root",y:0,points:0},{id:"parent",y:1,points:0},{id:"child",y:2,points:0}],flowEdges=[["parent","root"],["child","parent"]];
console.assert(hasActiveUpperConnection(flowNodes[0],flowNodes,flowEdges)&&!hasActiveUpperConnection(flowNodes[2],flowNodes,flowEdges),"roots must be selectable but connected children need an invested talent above");
flowNodes[1].points=1;
console.assert(hasActiveUpperConnection(flowNodes[2],flowNodes,flowEdges)&&!hasActiveUpperConnection(flowNodes[2],flowNodes,flowEdges,"parent"),"one invested upper connection must unlock the child and block breaking refunds");
flowNodes[2].threshold=2;
console.assert(!canSelectNode(flowNodes[2],flowNodes,flowEdges,1,3)&&pathState(flowNodes[1],flowNodes[2],flowNodes,flowEdges,2,3)==="available","green paths must only lead to currently selectable talents");
flowNodes[2].points=1;
console.assert(pathState(flowNodes[1],flowNodes[2],flowNodes,flowEdges,2,3)==="active","connections between leveled talents must be active");
const passiveNodes=[{points:4,cost:1},{points:0,max:1,cost:0,passive:true,threshold:5}];syncPassives(passiveNodes);
console.assert(passiveNodes[1].points===0&&!canSelectNode(passiveNodes[1],passiveNodes,[],4,25),"locked passives must not be manually selectable");
passiveNodes[0].points=5;syncPassives(passiveNodes);
console.assert(passiveNodes[1].points===1,"passives must auto-learn at their requirement");
passiveNodes[0].points=4;syncPassives(passiveNodes);
console.assert(passiveNodes[1].points===0,"passives must unlearn below their requirement");
console.log("Talent editor checks passed.");
